export const componentList = [
    { label: 'accordion', href: '/accordion' },
    { label: 'alert', href: '/alert' },
    { label: 'breadcrumb', href: '/breadcrumb' },
    { label: 'button', href: '/button' },
    { label: 'card', href: '/card' },
    { label: 'carousel', href: '/carousel' },
    { label: 'checkbox', href: '/checkbox' },
    { label: 'chip', href: '/chip' },
    { label: 'combobox', href: '/combobox' },
    { label: 'date input', href: '/date-input' },
    { label: 'dialog', href: '/dialog' },
    { label: 'icon', href: '/icon' },
    { label: 'icon button', href: '/icon-button' },
    { label: 'menu', href: '/menu' },
    { label: 'menu bar', href: '/menu-bar' },
    { label: 'meter', href: '/meter' },
    { label: 'navigation-list', href: '/navigation-list' },
    { label: 'navigation-menu', href: '/navigation-menu' },
    { label: 'pin-input', href: '/pin-input' },
    {
        label: 'primitives',
        href: '/primitives',
        submenu: [{ label: 'link', href: '/primitives/link' }]
    },
    { label: 'radio', href: '/radio' },
    { label: 'range input', href: '/range-input' },
    { label: 'select', href: '/select' },
    { label: 'slider', href: '/slider' },
    { label: 'snackbar', href: '/snackbar' },
    { label: 'switch', href: '/switch' },
    { label: 'table', href: '/table' },
    { label: 'tabs', href: '/tabs' },
    { label: 'text input', href: '/text-input' },
    { label: 'toast', href: '/toast' },
    { label: 'tooltip', href: '/tooltip' },
    { label: 'treeview', href: '/treeview' },
    { label: 'window-splitter', href: '/window-splitter' }
];